const MUTE_STATUS = 1
const TIMEOUT_STATUS = 2
const KICK_STATUS = 3
const DEFAULT_MUTE_THRESHOLD = 5
const DEFAULT_TIMEOUT_THRESHOLD = 7
const DEFAULT_KICK_THRESHOLD = 9

module.exports = {
  MUTE_STATUS,
  TIMEOUT_STATUS,
  KICK_STATUS,
  DEFAULT_MUTE_THRESHOLD,
  DEFAULT_TIMEOUT_THRESHOLD,
  DEFAULT_KICK_THRESHOLD
}